name: "Build CI"

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        name: "Fetching Materials"
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      -
        name: Construction
        run: |
            echo "sup"
